remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Functional Resonance Analysis Method
description: FRAM - the FUNCTIONAL RESONANCE ANALYSIS METHOD for modelling non-trivial socio-technical systems
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
